### ISSUE TITLE
Zmenit Logo ve skinu

### ISSUE THREAD

**Issue by Gargy007** [Gargy007/skin.estuary.stream-cinema-2.leia#16]
- Zde pockat na sikovneho grafika
- Slo by ho pozadat o nove ikony i pro veci v hlavnim menu.
![image](https://user-images.githubusercontent.com/6661580/82631709-6fe8a880-9bf6-11ea-9320-409696e86c72.png)

**Comment by ja-kjub** [comment]
Co chceme ? 

- [ ] mat logo pre SC2+Estuary a bude pouzivany ako vyhradny skin ... co umozni uzsiu spolupracu plugin skin
- [ ]  riesit len logo v ramci skinu a tym Estuary ostava jednou z moznosti pre SC2? Cize univerzalna ico bez prepojenia na SC2

**Comment by ja-kjub** [comment]
![SC2_white (3) (7)](https://user-images.githubusercontent.com/66039552/83106479-d3724a80-a0bc-11ea-8199-d472da6d4f3f.jpg)

![SC2_white (3) (11)](https://user-images.githubusercontent.com/66039552/83106569-fdc40800-a0bc-11ea-922f-e34a706d3f05.png)

Chces cisto CB ?

**Comment by ja-kjub** [comment]
![SC2_white (3) (5)xxxx (1)](https://user-images.githubusercontent.com/66039552/83106897-8b9ff300-a0bd-11ea-9620-8b5d4a36f42a.png)

**Comment by Gargy007** [comment]
Cau,
 jeste nez jsem zjistil ze delas grafiku na SC2, jsem pozadal (protoze jako jediny mel napsano ze je grafik ve spolupraci) CzDaV3 🎃 o modifikaci ikonek.

Nejde mi jen o tuto hlavni nahore vedle napisu kodi (ty tvoje vypadaju dobre a sli by pekne pouzit), ale take o upravu ikonek v hlavnim menu at rozlisim filmy co jsou zakladni widget a filmy pro SC2

A jeste dalsi vec - proc nepouzivas Stream Cinema 2 , ale jen Stream Cinema ?

**Comment by Gargy007** [comment]
Mely bych se domluvit CzDaV3 🎃 co jiz ma a nema at se to nedela dvakrat.

**Comment by ja-kjub** [comment]
;) nemam svoji roly jen jsem pomoh s cim muzu... ok

**Comment by Gargy007** [comment]
Ja take nemam svoji roli, jen jsem chtel par ikonek :-)

A ve vysledku me nezalezi od koho - proste kdo ma cas, je ochotny a jde mu to. Kontakt a czdav3 jsem psal proto at se treba spolu domluvime a neduplikujem vasu pracu. Proste sa taha za jeden provaz.

**Comment by ja-kjub** [comment]
Moj koncept icon, ak mi sem nahras zdroj z kodi 18 ideal 19ky ;) ak k nej mas pristup bude to super, skusam sa k nemu dostat aj ja.

![G8N6BW (1) (1)](https://user-images.githubusercontent.com/66039552/83134674-fa447700-a0e4-11ea-8195-cdd5adfb1b39.png)

**Comment by ja-kjub** [comment]
Ja som s tym uplne v pohode mozeme napady hadzat sem ... zatial som nasiel toto > koncept

**Comment by Gargy007** [comment]
Cau,
 ja bych spise zachoval puvodni KODI, ale jen do nich doplnil SC2 (ve
stejnem formatu jak je logo - font atd - proste at to graficky vypada dobre
a je to brandovane na SC2 + KODI)

čt 28. 5. 2020 v 13:15 odesílatel ja-kjub <notifications@github.com> napsal:

**Comment by ja-kjub** [comment]
Nahras mi sem prosim zdrojak icon png? alebo v akom formate to kodi ma ? dakujem 18ku ideal 19kove icony

**Comment by Gargy007** [comment]
Jasne ze dam, ja myslel ze je mas, jsou zakomprimovane Textures.xbt souboru zde v repu.

Zde pridavam rozkomprimovany zip.

Puvodni ikony prosim zachovej, jedna se mi o pridani noveho setu, ktery zachova stejny nazev ale prida prefix "esc2_" ke stavajicimu nazvu.  Zatim hlavne v tomto adresari: Textures_unpack\icons\sidemenu\

Muj puvodni napad je doplnit stavajici ikony o logo (text) "SC2"

Jinak fantazii a napadum se meze nekladou.
[Textures_unpack.zip](https://github.com/Gargy007/skin.estuary.stream-cinema-2.leia/files/4699773/Textures_unpack.zip)

**Comment by Gargy007** [comment]
Verim ze uz toto muze uzavrit.
