### ISSUE TITLE
Prozkoumat moznost prochazeni A-Z seznamu ve widgetu podle pluginu

### ISSUE THREAD

**Issue by Gargy007** [Gargy007/skin.estuary.stream-cinema-2.leia#20]
Toto je spis takova investigace - nejsem si jisty zda to pujde :-)

![image](https://user-images.githubusercontent.com/6661580/82637604-6a468f00-9c05-11ea-91a5-f14d4c3ab2c9.png)

**Comment by ja-kjub** [comment]
A, AA, AAA priamo vo widgete, hodi ta to potom do zoznamu prva polozka nemude "Hlavne menu" ale "Naspat" (na miesto odkial si prisiel, cize asi hlavna obrazovka s widgetmi) 

Hlavne menu ktore vedie k zoznamu vsetkych kategorii je dost matuce celkovo, lebo sa nevies lahko dostat na uvodnu obrazovku skinu.

**Comment by Gargy007** [comment]
AZ seznam zrusen z hlavniho widgetu
