### ISSUE TITLE
Zkontrolovat zda tam nejsou chyby nahlasene kjub :-)

### ISSUE THREAD

**Issue by Gargy007** [Gargy007/skin.estuary.stream-cinema-2.leia#22]
![image](https://user-images.githubusercontent.com/6661580/82987680-406fdc80-9ff8-11ea-94b6-a24d9351fa50.png)

**Comment by Gargy007** [comment]
Tlacitko search opraveno

**Comment by ja-kjub** [comment]
**Movie >** 
A-Z nereaguje vubec, 
Genre > nereaguji vubec 

**Series >** 
A-Z otvori sa list > file/playlist/videoaddons a sc2 zaloguje error 
Genre > funguji 



**SC2 menu >** popular series  prve tlacitko ("Next page 1/23") zmena nazvu na **"full list" / cely zoznam**
lebo takto to zavadza ci tie filmy v zozname uz su ako keby 1/23 a ked tam prides tak zrazu si myslis ze uz si na 2/23 ale hore vidis zlozku 2/23  VLAVO hore nevidis ziadnu presnu polohu

**Druhe tlacitko Main manu** vo widgete treba vyhodit > sipka dolava ta tam privedie.
**Prve tlacitko** Next page premenovat na full list > ale full list zacat uz naloadovanymi polozkami vo widgete cize **stranou 1** 

NA koniec widgetu dat tiez tlacitko full list ale prelinkovat na **stranu 2**

**Comment by Gargy007** [comment]
A-Z : docasne vypnute, problemy s nazvy adresaru
Genre - v posledni verzi na GITU funguje 

S tim tlacitkem ja nic neudelam - bud to nejde  nebo to ja neumim. Musela by se udelat zmena pluginu o kterou jiz je zazadano.

Oboji dvoji ty tlacitka Main Menu in next page je stejny pribeh jako prdchozi dotaz, je to vec pluginu a ja na to nemam moc vliv - bohuzel. Plugin je optimalizovany na pouzivani zakladniho Estuary, ale uz jsme si o zmenu zazadali.

Zase stejna story - ja neumim prehazovat poradi polozek v listu (dat tlacitko na konec).

Moc jsem te nepotesil, ale tento ticket zavru, to co jsi chte a mohl jsem bud je udelane nebo v jinem ticketu dablovane.
