### ISSUE TITLE
Rozsirene hladanie

### ISSUE THREAD

**Issue by ja-kjub** [Gargy007/skin.estuary.stream-cinema-2.leia#24]
ked kliknes na search (lupa) tak miesto OK ma 3 tlacitka Hladaj film, Hladaj serial, Hladaj Ostatne(herec reziser....) ... velmi to pomoze v sprehladneni vysledkov hladania.

**Comment by Gargy007** [comment]
Toto je zalezitost pluginu a ne skinu. Bohuzel musim zavrit
