### ISSUE TITLE
popular widget suffle top 50 ?

### ISSUE THREAD

**Issue by ja-kjub** [Gargy007/skin.estuary.stream-cinema-2.leia#25]
widgety mozu naloadovat az 50 thumbnailov ... ale stale je zachovane to iste poradie ... da sa tam vlozit nahodny algorytmus pre top 50 ?

**Comment by Gargy007** [comment]
Ahoj, bohuzel ve skinu ja s tim moc nenadelam. Zkus to dat jako navrh tvurcum pluginu.
