### ISSUE TITLE
Cesta / triedenie / pozice 

### ISSUE THREAD

**Issue by ja-kjub** [Gargy007/skin.estuary.stream-cinema-2.leia#26]
1 jdu Series > Genre > Anime ... vidim animovane serialy 

ale hore vlavo MOVIES /Stream Cinema 2 (pritom uz som v serialoch)? najdem serial otvorim a hore vlavo sa zmeni TV Shows / Stream Cinema 2 ... treba opravit v tom prvom kroku

2 Lave menu > Series > otvorim enter a vidim vlavo hore Videos  > A-Z vidim Videos > D (Videos) > DA (videos) > DAB (videos) > otvorim dalej vylistuju sa mi serialy ale hore vlavo je MOVIES / Stream Cinema.

**Comment by Gargy007** [comment]
POlde abecedy a zanru odstraneno ze skinu (pridano serial/movie menu jako nahrada).


Duvod, neslo to rozchodit bez zmeny v pluginu a take to nebylo hezke.
