### ISSUE TITLE
Watch history hlavne SC2 widget ano, menu polozka ano

### ISSUE THREAD

**Issue by ja-kjub** [Gargy007/skin.estuary.stream-cinema-2.leia#27]
urcite ju nechaj v SC2 main (hlavna polozka) a aj v bocnom menu
vo widgete uprav filter na "len serialy" a pridaj prvu polozku Filmy. Ak si niekto chce zaspominat na filmy klinke si prvu polozku a ta ho presmeruje na zoznam filmov co uz videl a 80% bude dalej scrolovat widget k oblubenemu serialu co ma rozpozerany 

tych 20% pojde najst svoj nedopozeranej film aby pokracovala

**Comment by Gargy007** [comment]
Ja nedokazu rozlisit v historii jen serialy nebo jen filmy :-(
