### ISSUE TITLE
chybí kurzor

### ISSUE THREAD

**Issue by terzdek** [Gargy007/skin.estuary.stream-cinema-2.leia#6]
Ahoj, nevím čím to, ale po instalaci tohoto parádního skinu se mi v kodi neukazuje kurzor. Jedu pod WIN 7 s kodi 18.6.

**Comment by MarekGargulak** [comment]
Pošleš mi prosím log.
Díky

**Comment by terzdek** [comment]
Není problem, jen je to na pracovním notesu, tak až se k němu dostanu. Třeba
je to ale jen na mém stroji. 

---------- Původní zpráva ----------
Od: MarekGargulak 
Datum: 17. 5. 2020 v 18:35:47
Předmět: Re: [Gargy007/skin.estuary.stream-cinema-2.leia] chybí kurzor (#6)






Pošleš mi prosím log.


Díky





—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/Gargy007/skin.estuary.stream-cinema-2.leia/issues/6#issuecomment-629825405)
, or unsubscribe

**Comment by terzdek** [comment]
[kodi.log](https://github.com/Gargy007/skin.estuary.stream-cinema-2.leia/files/4658183/kodi.log)
Ahoj, tady je LOG. Předem díky moc

**Comment by terzdek** [comment]
Takže, hledal jsem několik dní, co by to mohlo dělat. Voala není to problém ve skinu. Je to v nastavení: Vstup: Povolit podporu myši a dotykové obrazovky. Nezlob se, že jsem otravoval.
