### ISSUE TITLE
Chyba odkazu žánru

### ISSUE THREAD

**Issue by MiroslavCZ** [Gargy007/skin.estuary.stream-cinema-2.leia#7]
Ahoj, hlásím chybu v sekci "CS2 Filmy" (najetí myší) a na položku žánr (klik) vyhazuje Cinema Stream 2 chybu, CS2 1.3.5 beta, 18.6 kodi, skin 3.0.0.a1
![chyba skin](https://user-images.githubusercontent.com/65082560/82158434-18f67280-9888-11ea-8f0e-b69a19cfc22a.jpg)

**Comment by MiroslavCZ** [comment]
ver 3.0.0.a1

**Comment by Gargy007** [comment]
Uz je vyreseno ve verzi 3.0.0.alpha2 , ale jeste to neni venku, resi se jeste kosmeticke drobnosti, at oznate rozdil. od minule verze
