### ISSUE TITLE
moznost vypnutí hlavni menu a dalsi viz screen

### ISSUE THREAD

**Issue by thomas377** [Gargy007/skin.estuary.stream-cinema-2.leia#9]
možnost vypnutí položky hlavni menu, dalsi stranka a popisky SC2 u Filmy a Serialy, diky
![IMG_20200519_214343](https://user-images.githubusercontent.com/65625460/82372226-e54c5180-9a1b-11ea-81e1-26338ed05d0c.jpg)

**Comment by MarekGargulak** [comment]
Pracuji na reseni :-)
![kodi](https://user-images.githubusercontent.com/65391427/82376293-25aece00-9a22-11ea-91ef-61b4d7855a66.png)

**Comment by thomas377** [comment]
> Pracuji na reseni :-)
> ![kodi](https://user-images.githubusercontent.com/65391427/82376293-25aece00-9a22-11ea-91ef-61b4d7855a66.png)

Super, díky moc!

**Comment by Gargy007** [comment]
Vypada to ze reseni nakonec by nemel delat skin, ale plugin samotny. Pockame na vyreseni tohoto ticketu a pok se updatne i skin aby toho vyuzil: https://git.hotshot.sk/stream-cinema-2.0/plugin-video-stream-cinema-2/-/issues/97 .

**Comment by ja-kjub** [comment]
Ahoj, "Dalsia stranka" by som presunul na koniec, s funkciou znovu nacitat pozicie vo wiegete +pocet uz videnych (cislo sa das feedovat z nastaveni) a takto umoznit ludom nech aspon 2x 3x nacitaju nove veci priamo vo widgete

**Comment by Gargy007** [comment]
Uz to tam neni, novy SC2 plugin toto odstranil.
